// Code generated by MockGen. DO NOT EDIT.
// Source: url.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUrlSaver is a mock of UrlSaver interface.
type MockUrlSaver struct {
	ctrl     *gomock.Controller
	recorder *MockUrlSaverMockRecorder
}

// MockUrlSaverMockRecorder is the mock recorder for MockUrlSaver.
type MockUrlSaverMockRecorder struct {
	mock *MockUrlSaver
}

// NewMockUrlSaver creates a new mock instance.
func NewMockUrlSaver(ctrl *gomock.Controller) *MockUrlSaver {
	mock := &MockUrlSaver{ctrl: ctrl}
	mock.recorder = &MockUrlSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlSaver) EXPECT() *MockUrlSaverMockRecorder {
	return m.recorder
}

// SaveUrl mocks base method.
func (m *MockUrlSaver) SaveUrl(ctx context.Context, urlToSave, alias string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUrl", ctx, urlToSave, alias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUrl indicates an expected call of SaveUrl.
func (mr *MockUrlSaverMockRecorder) SaveUrl(ctx, urlToSave, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUrl", reflect.TypeOf((*MockUrlSaver)(nil).SaveUrl), ctx, urlToSave, alias)
}

// MockUrlRedirecter is a mock of UrlRedirecter interface.
type MockUrlRedirecter struct {
	ctrl     *gomock.Controller
	recorder *MockUrlRedirecterMockRecorder
}

// MockUrlRedirecterMockRecorder is the mock recorder for MockUrlRedirecter.
type MockUrlRedirecterMockRecorder struct {
	mock *MockUrlRedirecter
}

// NewMockUrlRedirecter creates a new mock instance.
func NewMockUrlRedirecter(ctrl *gomock.Controller) *MockUrlRedirecter {
	mock := &MockUrlRedirecter{ctrl: ctrl}
	mock.recorder = &MockUrlRedirecterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlRedirecter) EXPECT() *MockUrlRedirecterMockRecorder {
	return m.recorder
}

// GetUrl mocks base method.
func (m *MockUrlRedirecter) GetUrl(ctx context.Context, alias string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUrl", ctx, alias)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUrl indicates an expected call of GetUrl.
func (mr *MockUrlRedirecterMockRecorder) GetUrl(ctx, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUrl", reflect.TypeOf((*MockUrlRedirecter)(nil).GetUrl), ctx, alias)
}
