syntax = "proto3";

package url_shortening_service;

option go_package = "github.com/VadimShara/url_shortening_service/api/pb;url_shortening_service_pb";

service Url {
    rpc SaveUrl (SaveUrlRequest) returns (SaveUrlResponse);
    rpc RedirectUrl (RedirectUrlRequest) returns (RedirectUrlResponse);
}

message SaveUrlRequest {
    string url = 1;
}

message SaveUrlResponse {
    string alias = 1;
}

message RedirectUrlRequest {
    string alias = 1;
}

message RedirectUrlResponse {
    string url = 1;
}